language: python
python:
  - "3.6"
  - "3.5"
  - "3.4"
  - "2.7"
install:
  - pip install -r ./tests-requirements.txt
  - pip install coveralls
script:
  - py.test --cov=heroku3 --cov-report=html --cov-branch
after_success:
- coveralls
- codecov
